/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type MemberMemberType = typeof MemberMemberType[keyof typeof MemberMemberType];


export const MemberMemberType = {
  retail: 'retail',
  professional: 'professional',
} as const;

export interface Member {
  id: number;
  clerkId: string;
  displayName: string;
  avatarUrl?: string | null;
  bio?: string | null;
  memberType: MemberMemberType;
  country?: string | null;
  joinedAt: string;
}

export interface MemberUpdate {
  /** @minLength 1 */
  displayName?: string;
  bio?: string;
  country?: string;
}

export interface EquityPoint {
  date: string;
  valueZar: number;
}

export interface DashboardSummary {
  portfolioValueZar: number;
  totalPnlZar: number;
  totalPnlPct: number;
  winRate: number;
  openPositions: number;
  totalTrades: number;
  monthlyPnlZar: number;
  equityCurve: EquityPoint[];
}

export type ActivityItemType = typeof ActivityItemType[keyof typeof ActivityItemType];


export const ActivityItemType = {
  trade_opened: 'trade_opened',
  trade_closed: 'trade_closed',
  lesson_completed: 'lesson_completed',
  rank_changed: 'rank_changed',
  deposit: 'deposit',
  withdrawal: 'withdrawal',
} as const;

export interface ActivityItem {
  id: number;
  type: ActivityItemType;
  title: string;
  description: string;
  occurredAt: string;
}

export type CourseLevel = typeof CourseLevel[keyof typeof CourseLevel];


export const CourseLevel = {
  beginner: 'beginner',
  intermediate: 'intermediate',
  advanced: 'advanced',
} as const;

export interface Course {
  id: number;
  title: string;
  description: string;
  level: CourseLevel;
  lessonCount: number;
  durationMinutes: number;
  category: string;
  coverEmoji: string;
  completedLessons?: number;
}

export type LessonType = typeof LessonType[keyof typeof LessonType];


export const LessonType = {
  video: 'video',
  article: 'article',
  quiz: 'quiz',
} as const;

export interface Lesson {
  id: number;
  courseId: number;
  title: string;
  durationMinutes: number;
  orderIndex: number;
  type: LessonType;
  isCompleted?: boolean;
}

export type CourseDetailLevel = typeof CourseDetailLevel[keyof typeof CourseDetailLevel];


export const CourseDetailLevel = {
  beginner: 'beginner',
  intermediate: 'intermediate',
  advanced: 'advanced',
} as const;

export interface CourseDetail {
  id: number;
  title: string;
  description: string;
  level: CourseDetailLevel;
  lessonCount: number;
  durationMinutes: number;
  category: string;
  coverEmoji: string;
  completedLessons?: number;
  lessons: Lesson[];
}

export interface AcademyProgress {
  totalLessons: number;
  completedLessons: number;
  totalCourses: number;
  completedCourses: number;
  streakDays: number;
  xpPoints: number;
}

export interface LessonCompletion {
  lessonId: number;
  completedAt: string;
  xpAwarded: number;
}

export type LeaderboardEntryBadge = typeof LeaderboardEntryBadge[keyof typeof LeaderboardEntryBadge];


export const LeaderboardEntryBadge = {
  gold: 'gold',
  silver: 'silver',
  bronze: 'bronze',
  top10: 'top10',
  none: 'none',
} as const;

export interface LeaderboardEntry {
  rank: number;
  memberId: number;
  displayName: string;
  avatarUrl?: string | null;
  pnlZar: number;
  pnlPct: number;
  winRate: number;
  totalTrades: number;
  badge: LeaderboardEntryBadge;
  isCurrentUser?: boolean;
}

export type GetLeaderboardParams = {
period?: GetLeaderboardPeriod;
};

export type GetLeaderboardPeriod = typeof GetLeaderboardPeriod[keyof typeof GetLeaderboardPeriod];


export const GetLeaderboardPeriod = {
  monthly: 'monthly',
  alltime: 'alltime',
} as const;

