/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Get current member profile
 */
export const GetMeResponse = zod.object({
  "id": zod.number(),
  "clerkId": zod.string(),
  "displayName": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "memberType": zod.enum(['retail', 'professional']),
  "country": zod.string().nullish(),
  "joinedAt": zod.coerce.date()
})


/**
 * @summary Update member profile
 */



export const UpdateMeBody = zod.object({
  "displayName": zod.string().min(1).optional(),
  "bio": zod.string().optional(),
  "country": zod.string().optional()
})

export const UpdateMeResponse = zod.object({
  "id": zod.number(),
  "clerkId": zod.string(),
  "displayName": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "bio": zod.string().nullish(),
  "memberType": zod.enum(['retail', 'professional']),
  "country": zod.string().nullish(),
  "joinedAt": zod.coerce.date()
})


/**
 * @summary Dashboard summary stats and portfolio snapshot
 */
export const GetDashboardResponse = zod.object({
  "portfolioValueZar": zod.number(),
  "totalPnlZar": zod.number(),
  "totalPnlPct": zod.number(),
  "winRate": zod.number(),
  "openPositions": zod.number(),
  "totalTrades": zod.number(),
  "monthlyPnlZar": zod.number(),
  "equityCurve": zod.array(zod.object({
  "date": zod.string(),
  "valueZar": zod.number()
}))
})


/**
 * @summary Recent activity feed for the current member
 */
export const GetActivityResponseItem = zod.object({
  "id": zod.number(),
  "type": zod.enum(['trade_opened', 'trade_closed', 'lesson_completed', 'rank_changed', 'deposit', 'withdrawal']),
  "title": zod.string(),
  "description": zod.string(),
  "occurredAt": zod.coerce.date()
})
export const GetActivityResponse = zod.array(GetActivityResponseItem)


/**
 * @summary List all academy courses
 */
export const ListCoursesResponseItem = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string(),
  "level": zod.enum(['beginner', 'intermediate', 'advanced']),
  "lessonCount": zod.number(),
  "durationMinutes": zod.number(),
  "category": zod.string(),
  "coverEmoji": zod.string(),
  "completedLessons": zod.number().optional()
})
export const ListCoursesResponse = zod.array(ListCoursesResponseItem)


/**
 * @summary Get a course with its lessons
 */
export const GetCourseParams = zod.object({
  "courseId": zod.coerce.number()
})

export const GetCourseResponse = zod.object({
  "id": zod.number(),
  "title": zod.string(),
  "description": zod.string(),
  "level": zod.enum(['beginner', 'intermediate', 'advanced']),
  "lessonCount": zod.number(),
  "durationMinutes": zod.number(),
  "category": zod.string(),
  "coverEmoji": zod.string(),
  "completedLessons": zod.number().optional(),
  "lessons": zod.array(zod.object({
  "id": zod.number(),
  "courseId": zod.number(),
  "title": zod.string(),
  "durationMinutes": zod.number(),
  "orderIndex": zod.number(),
  "type": zod.enum(['video', 'article', 'quiz']),
  "isCompleted": zod.boolean().optional()
}))
})


/**
 * @summary Get current member academy progress
 */
export const GetAcademyProgressResponse = zod.object({
  "totalLessons": zod.number(),
  "completedLessons": zod.number(),
  "totalCourses": zod.number(),
  "completedCourses": zod.number(),
  "streakDays": zod.number(),
  "xpPoints": zod.number()
})


/**
 * @summary Mark a lesson complete for the current member
 */
export const CompleteLessonParams = zod.object({
  "lessonId": zod.coerce.number()
})

export const CompleteLessonResponse = zod.object({
  "lessonId": zod.number(),
  "completedAt": zod.coerce.date(),
  "xpAwarded": zod.number()
})


/**
 * @summary Ranked trader leaderboard
 */
export const getLeaderboardQueryPeriodDefault = `monthly`;

export const GetLeaderboardQueryParams = zod.object({
  "period": zod.enum(['monthly', 'alltime']).default(getLeaderboardQueryPeriodDefault)
})

export const GetLeaderboardResponseItem = zod.object({
  "rank": zod.number(),
  "memberId": zod.number(),
  "displayName": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "pnlZar": zod.number(),
  "pnlPct": zod.number(),
  "winRate": zod.number(),
  "totalTrades": zod.number(),
  "badge": zod.enum(['gold', 'silver', 'bronze', 'top10', 'none']),
  "isCurrentUser": zod.boolean().optional()
})
export const GetLeaderboardResponse = zod.array(GetLeaderboardResponseItem)


/**
 * @summary Current member leaderboard rank
 */
export const GetMyRankResponse = zod.object({
  "rank": zod.number(),
  "memberId": zod.number(),
  "displayName": zod.string(),
  "avatarUrl": zod.string().nullish(),
  "pnlZar": zod.number(),
  "pnlPct": zod.number(),
  "winRate": zod.number(),
  "totalTrades": zod.number(),
  "badge": zod.enum(['gold', 'silver', 'bronze', 'top10', 'none']),
  "isCurrentUser": zod.boolean().optional()
})


